# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8d9c085f-c3ab-4e76-8c7d-212f9b709c37";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D2EA-AAE4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/6d1bca23-3e89-40fb-8028-a160a2be6f17" =
    { device = "/dev/disk/by-uuid/6d1bca23-3e89-40fb-8028-a160a2be6f17";
      fsType = "ext4";
      options = [ "users" "nofail" "exec" "x-gvfs-show" ];
    };

  fileSystems."/mnt/a1b4840e-ce31-451f-9bc9-f34908ba2e96" =
    { device = "/dev/disk/by-uuid/a1b4840e-ce31-451f-9bc9-f34908ba2e96";
      fsType = "ext4";
      options = [ "users" "nofail" "exec" "x-gvfs-show" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1b5156d1-41b4-4f83-8c87-727c4984f8bc"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp45s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
